volumes/app/src/account/urls.py
from django.urls import path
from .views import (
    ArticleList,
    ArticleCreate,
    ArticleUpdate,
    ArticleDelete,
    Profile,
)


app_name = "account"

urlpatterns = [
    path('', ArticleList.as_view(), name="userHome"),
    path('article/create/', ArticleCreate.as_view(), name="article-create"),
    path('article/update/<int:pk>/', ArticleUpdate.as_view(), name="article-update"),
    path('article/delete/<int:pk>/', ArticleDelete.as_view(), name="article-delete"),
    path('profile/', Profile.as_view(), name="profile"),
]

volumes/app/src/blog/urls.py
from django.urls import path
from .views import (
    home,
    articleDetails,
    categoryPage,
    authorPage,
    articlePreview,
)


app_name = "blog"
urlpatterns = [
    path('', home, name="home-root"),
    path('home/', home, name="home"),
    path('home/page/<int:page>/', home, name="home"),
    path('article/<slug:slug>/', articleDetails, name="articleDetails"),
    path('preview/<int:pk>/', articlePreview.as_view(), name="articlePreview"),
    path('category/<slug:slug>/', categoryPage, name="categoryPage"),
    path('category/<slug:slug>/page/<int:page>/', categoryPage, name="categoryPage"),
    path('author/<slug:username>/', authorPage, name="authorPage"),
    path('author/<slug:username>/page/<int:page>/', authorPage, name="authorPage"),
]

volumes/app/src/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate

app_name = "config"
urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('blog.urls')),
    path('login/', Login.as_view(), name='login'),
    path('signup/', Register.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]


# config for serving uploaded files during development and debug

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volumes/app/src/blog/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils import timezone
from extensions.utils import jalali_datetime
from django.utils.html import format_html
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment




# Custom Managers

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')




class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)




# Create your models here.

class IpAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="IP Address")

    class Meta:
        verbose_name = "IP Address"
        verbose_name_plural = "IP Addresses"

    def __str__(self):
        return self.ip_address




class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    status = models.BooleanField(default=True, verbose_name="Active?")
    position = models.IntegerField(verbose_name="position")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['position']

    def __str__(self):
        return self.title

    objects = CategoryManager()




class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('i', 'Investigating'),
        ('r', 'Returned'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="Author")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, verbose_name="Category", related_name="articles")
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_VIP = models.BooleanField(default=False, verbose_name="VIP")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IpAddress, through="ArticleHits", blank=True, related_name="articles", verbose_name="Hits")

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        ordering = ["-publish"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:userHome")

    def jDateTime(self):
        return jalali_datetime(self.publish)
    jDateTime.short_description = "Date & Time"

    def thumbnail_tag(self):
        return format_html("<img width=100 height=70 style='border-radius: 5px;' src='{0}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = "Thumbnail"

    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "Category"

    objects = ArticleManager()




class ArticleHits(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IpAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

volumes/app/src/blog/views.py
from account.models import User
from django.views.generic import DetailView
from account.mixins import AuthorAccessMixin_draftPreview
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article, Category


# Create your views here.

def home(request, page=1):
    article_list = Article.objects.published()
    paginator = Paginator(article_list , 2)
    #page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    context = {
        "articles": page_obj,
    }
    return render(request, "blog/homePage.html", context)


def articleDetails(request, slug):
    
    article = get_object_or_404(Article.objects.published(), slug=slug)

    context = {
        "article": article,
    }

    ip_address = request.user.ip_address

    if ip_address not in article.hits.all():
        article.hits.add(ip_address)

    return render(request,"blog/post.html", context)


class articlePreview(AuthorAccessMixin_draftPreview, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)
    template_name = "blog/post.html"


def categoryPage(request, slug, page=1):
    category = get_object_or_404(Category.objects.active(), slug=slug)
    article_list = category.articles.published()
    paginator = Paginator(article_list , 2)
    page_obj = paginator.get_page(page)
    context = {
        "category" : category,
        "articles" : page_obj
    }
    return render(request, "blog/categoryPage.html", context)


def authorPage(request, username, page=1):
    author = get_object_or_404(User, username=username)
    article_list = author.articles.published()
    paginator = Paginator(article_list , 4)
    page_obj = paginator.get_page(page)
    context = {
        "author" : author,
        "articles" : page_obj
    }
    return render(request, "blog/author.html", context)

volumes/app/src/comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

volumes/app/src/templates/blog/author.html
{% extends 'blog/page.html' %}
{% load static %}
{% block title %}
    Author | {{author.get_full_name}}
{% endblock %}

{% block header %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h3 class="fw-bolder" style="color: var(--bs-body-color);">Author: {{author.get_full_name}}</h3>
        </div>
    </div>
</header>
{% endblock %}

{% block featured_post %}
{% endblock %}

<!-- Pagination-->
{% block first_page %}
    {% url 'blog:authorPage' author.username 1 %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:authorPage' author.username articles.previous_page_number %}
{% endblock %}
{% block next_page %}
    {% url 'blog:authorPage' author.username articles.next_page_number %}
{% endblock %}
{% block last_page %}
    {% url 'blog:authorPage' author.username articles.paginator.num_pages %}
{% endblock %}

volumes/app/src/templates/blog/base.html
{% load static %}
{% load partial_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        {% comment %} <link rel="icon" type="static/image/x-icon" href="{% static '/blog/assets/favicon.ico' %}" /> {% endcomment %}
        <link rel="apple-touch-icon" sizes="180x180" href="{% static '/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static '/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static '/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static '/favicon/site.webmanifest' %}">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static '/blog/css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <style>
            .home-header{
                background-image: url("{% static 'blog/images/header-bg.jpg' %}");
                background-position: center;
                height: 95vh;
                background-size: cover;
            }
        </style>
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blog:home' %}">Cactus &#127797;</a>
                {% if user.is_authenticated %}
                    <div>
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 list-group-horizontal">
                            <li class="nav-item border border-white rounded text-center me-2 ps-1 pe-1"><a target="_blank" class="nav-link" href="{% url 'account:userHome' %}">Account</a></li>
                            <li class="nav-item"><a target="_self" class="nav-link text-center text-white" href="{% url 'logout' %}">Log Out</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div>
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 list-group-horizontal">
                            <li class="nav-item border border-white rounded text-center me-2 ps-1 pe-1"><a target="_blank" class="nav-link" href="{% url 'login' %}">Log In</a></li>
                            <li class="nav-item"><a target="_blank" class="nav-link text-center text-white" href="{% url 'signup' %}">Sign Up</a></li>
                        </ul>
                    </div>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a target="_blank" class="nav-link" href="https://EhsanHo.dev">Contact</a></li>
                        <li class="nav-item"><a target="_blank" class="nav-link" href="https://github.com/EhsanHoDev/DjangoSample">Source</a></li>
                        {% comment %} <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li> {% endcomment %}
                    </ul>
                </div>
            </div>
        </nav>

{% block main %}
{% endblock %}

                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    {% cat_tags %}
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets.</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center"><span class="text-white">GitHub: </span><a style="text-decoration:none" target="_blank" href="https://github.com/EhsanHoDev/DjangoSample">This project is open source. Click on me!</a></p>
                <p class="m-0 text-center"><span class="text-white">By: </span><a style="text-decoration:none" target="_blank" href="https://EhsanHo.dev"><b>Ehsan Ho</b></a></p>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    </body>
</html>

volumes/app/src/templates/blog/categoryPage.html
{% extends 'blog/page.html' %}
{% load static %}
{% block title %}
    Category | {{category.title}}
{% endblock %}

{% block header %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h3 class="fw-bolder" style="color: var(--bs-body-color);">Category: {{category.title}}</h3>
        </div>
    </div>
</header>
{% endblock %}

{% block featured_post %}
{% endblock %}

<!-- Pagination-->
{% block first_page %}
    {% url 'blog:categoryPage' category.slug 1 %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:categoryPage' category.slug articles.previous_page_number %}
{% endblock %}
{% block next_page %}
    {% url 'blog:categoryPage' category.slug articles.next_page_number %}
{% endblock %}
{% block last_page %}
    {% url 'blog:categoryPage' category.slug articles.paginator.num_pages %}
{% endblock %}

volumes/app/src/templates/blog/homePage.html
{% extends 'blog/page.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block header %}
<!-- Page header with logo and tagline-->
<header class="py-5 bg-light border-bottom mb-4 home-header">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder" style="color: var(--bs-body-bg);">Welcome to Cactus!</h1>
        </div>
    </div>
</header>
{% endblock %}

{% block featured_post %}
<!-- Featured blog post-->
<div class="card mb-4">
    <a href="#!"><img class="card-img-top" src="{% static 'blog/images/featured.jpg' %}" alt="..." /></a>
    <div class="card-body">
        <div class="small text-muted">January 1, 2021</div>
        <h2 class="card-title">Featured Post Title</h2>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
        <a class="btn btn-primary" href="#!">Read more →</a>
    </div>
</div>
{% endblock %}
 
<!-- Pagination-->
{% block first_page %}
    {% url 'blog:home' 1 %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:home' articles.previous_page_number %}
{% endblock %}
{% block next_page %}
    {% url 'blog:home' articles.next_page_number %}
{% endblock %}
{% block last_page %}
    {% url 'blog:home' articles.paginator.num_pages %}
{% endblock %}

volumes/app/src/templates/blog/page.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% block title %}
{% endblock %}

{% block main %}

{% block header %}
{% endblock %}

<!-- Page content-->
<div class="container">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">
            
{% block featured_post %}
{% endblock %}

    <!-- Nested row for non-featured blog posts-->
    {% for article in articles %}
    <div class="row">
        <div class="col-lg-6">
            <!-- Blog post-->
            <div class="card mb-4" style="max-width: 100%;">
                <a href="{% url 'blog:articleDetails' article.slug %}"><img class="card-img-top" src="{{article.thumbnail.url}} " alt="..." /></a>
                <div class="card-body">
                    <div class="small text-muted" style="direction: rtl; text-align: left;">{{article.jDateTime}}</div>
                    <h2 class="card-title h4">{{article.title}}
                    {% if article.is_VIP %}
                        <span class="badge bg-danger"  style="font-size: 10px">VIP</span>
                    {% endif %}
                    </h2>
                    <p class="card-text">
                        {% if article.is_VIP %}
                            {% if user.is_authenticated and user.is_VIP_user or user.is_superuser or user.is_authenticated and user.is_author %}
                                {{article.description | striptags | truncatewords:20}}
                            {% else %}
                                {{article.description | striptags | truncatewords:20}}
                                <p class="text-center bg-light w-75 mx-auto py-2">This article is VIP. <a href="#!" style="text-decoration: none">Upgrade your account.</a></p>
                            {% endif %}
                        {% else %}
                            {{article.description | striptags | truncatewords:20}}
                        {% endif %}
                    </p>
                    <div class="small pb-3" style="font-size:13px">
                        {% ratings article  %}
                    </div>
                    <p class="small text-muted mb-0">Written by:
                        {% if article.author.get_full_name %}
                            <a style="text-decoration: none;" href="{% url 'blog:authorPage' article.author %}">{{article.author.get_full_name}}</a>
                        {% else %}
                            <a style="text-decoration: none;" href="{% url 'blog:authorPage' article.author %}">{{article.author.username}}</a>
                        {% endif %}
                    </p>
                    <small class="text-primary">Views: {{article.hits.count}}</small>
                    <!-- Post categories-->
                    <div class="mb-1 mt-2">
                        {% for category in article.category.active %}
                        <a class="text-decoration-none" href="{% url 'blog:categoryPage' category.slug %}">#{{category.title}}</a>
                        {% endfor %}
                    </div>
                    <a class="btn btn-primary" href="{% url 'blog:articleDetails' article.slug %}">Read more →</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    
    <!-- Pagination-->
    <nav aria-label="Pagination">
        <hr class="my-0" />
        <ul class="pagination justify-content-center my-4">
            {% if articles.has_previous %}
            <li class="page-item"><a class="page-link" href="{% block first_page %}{% endblock %}">First</a></li>
            <li class="page-item"><a class="page-link" href="{% block previous_page %}{% endblock %}" tabindex="-1" aria-disabled="true">&larr; Newer</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">First</a></li>
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&larr; Newer</a></li>
            {% endif %}
            <li class="page-item disabled"><a style="color: black;" class="page-link" href="#" tabindex="-1" aria-disabled="true">Page {{articles.number}} of {{articles.paginator.num_pages}}</a></li>
            {% if articles.has_next %}
            <li class="page-item"><a class="page-link" href="{% block next_page %}{% endblock %}">Older &rarr;</a></li>
            <li class="page-item"><a class="page-link" href="{% block last_page %}{% endblock %}">Last</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Older &rarr;</a></li>
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Last</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
        
{% endblock %}

volumes/app/src/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% block title %}
    Post | {{article.title}}
{% endblock %}
{% block main %}

<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}
                    {% if article.is_VIP %}
                        <span class="badge bg-danger"  style="font-size: 12px">VIP</span>
                    {% endif %}
                    </h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2" style="direction: rtl; text-align: left;">{{article.jDateTime}}</div>
                    <small class="text-primary fw-bold">Views: {{article.hits.count}}</small>
                    <p class="small text-muted">Written by:
                        {% if article.author.get_full_name %}
                            <a style="text-decoration: none;" href="{% url 'blog:authorPage' article.author %}">{{article.author.get_full_name}}</a>
                        {% else %}
                            <a style="text-decoration: none;" href="{% url 'blog:authorPage' article.author %}">{{article.author.username}}</a>
                        {% endif %}
                    </p>
                    <!-- Post categories-->
                    <div>
                        {% for category in article.category.active %}
                        <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'blog:categoryPage' category.slug %}">{{category.title}}</a>
                        {% endfor %}
                    </div>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.thumbnail.url}}" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    {% if article.is_VIP %}
                        {% if user.is_authenticated and user.is_VIP_user or user.is_superuser or user.is_authenticated and user.is_author %}
                            <p class="fs-5 mb-4">{{article.description | safe | linebreaks}}</p>
                        {% else %}
                            <p class="fs-6 mb-4">{{article.description | striptags | truncatewords:40}}</p>
                            <p class="alert alert-warning text-center fs-5 mb-4 w-75 mx-auto">This article is VIP. <a class="alert-link" href="#!" style="text-decoration: none">Upgrade your account.</a></p>
                        {% endif %}
                    {% else %}
                        <p class="fs-5 mb-4">{{article.description | safe | linebreaks}}</p>
                    {% endif %}
                </section>
                <div class="py-4 w-50 mx-auto" style="background-color:#bdbbbb; border-radius:13px;">
                    <div class="text-center small">
                        {% ratings article %}
                    </div>
                </div>
            </article>

            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        {% render_comments article request %}
                        {% comment %} {% include_bootstrap %} {% endcomment %}
                    </div>
                </div>
            </section>

            {% comment %} <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form-->
                        <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                        <!-- Comment with nested comments-->
                        <div class="d-flex mb-4">
                            <!-- Parent comment-->
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                <!-- Child comment 1-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                    </div>
                                </div>
                                <!-- Child comment 2-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When you put money directly to a problem, it makes a good headline.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Single comment-->
                        <div class="d-flex">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                            </div>
                        </div>
                    </div>
                </div>
            </section> {% endcomment %}
            
        </div>
        
{% endblock %}